# .rubocop.yml

plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "Gemfile"

# クラスやモジュールにコメントを必須にしない
Style/Documentation:
  Enabled: false

# 文字列の凍結（# frozen_string_literal: true）を必須にしない
Style/FrozenStringLiteralComment:
  Enabled: false

# 1行の文字数制限を少し緩めにする（デフォルトは80）
Layout/LineLength:
  Max: 120

# メソッドの行数制限を少し緩めにする（デフォルトは10）
Metrics/MethodLength:
  Max: 20

# ブロックの行数制限を少し緩めにする
Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "spec/**/*" 
Rails/Exit:
  Exclude:
    - 'spec/rails_helper.rb'

# メソッドの複雑さ（AbcSize）の制限を少し緩めにする（デフォルトは17）
Metrics/AbcSize:
  Max: 25
