services:
  db:
    image: postgres:16
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # ↓ ここが重要！開発モードに強制指定
      RAILS_ENV: development
      # ↓ コンソール等でも常にこのURLを使うように指示
      DATABASE_URL: postgres://postgres:password@db:5432/app_development
  frontend:
    image: node:20-slim
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
    command: npm run dev
    tty: true
    stdin_open: true