services:
  # データベースの設定
  - type: db
    name: nomusup-db
    ipAllowList: [] 

  # バックエンド(Rails)の設定
  - type: web
    name: nomusup-api
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nomusup-db
          attribute: connectionString
      - key: RAILS_MASTER_KEY
        sync: false 